typography_spectrum: 0.43642115546390414
color:
  brandStrength: 0.6988286434207112
  lightness: 0.8811156821902841
  saturation: 0.48863836424425244
  rhythmicContrast: 0.28102078079245985
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
layout_spectrum: 0.389155455166474
author:
  name: Carlos Ruiz
  email: ruvaphotovideo@icloud.com
  url: www.ruvaphotovideo.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5198c07a-885a-4048-9182-dddfce4363db.jpg
name: RuVa Photo & Video
navigation:
  - name: Art Gallery
    id: 6dff909f-1d6d-4bde-b63b-0a11a0969c32
    type: content
title: RuVa Photo & Video
description: Photography and Video Solutions
